title: Type or Typo?
description: This website is a project for University
header_text: Type or Typo?
footer_text: Copyright 2020 Jemima Cox
header_feature_image: ../uploads/screenshot-2020-10-13-at-07.59.18.png
bannerheight: 20vmax
logo: ../uploads/type-or-typo-logo-2.png
favicon: ../uploads/screenshot-2020-10-01-at-19.46.43.png
gridlayout: false
fixednavbar: false
upzoom: true
