title: Type or Typo?
description: This website is a project for University
header_text: Type or Typo?
footer_text: Copyright 2020 Jemima Cox
header_feature_image: ../uploads/alice-in-wonderland-book-page-3-old-design-shop.jpg
bannerheight: 20vmax
logo: ../uploads/type-or-typo-logo-2.png
favicon: ""
gridlayout: false
fixednavbar: false
upzoom: true
